### ISSUE TITLE
checkstyle plugin failure

### ISSUE THREAD

**Issue by delanym** [wso2/carbon-parent#45]
**Description:**
The checkstyle plugin fails to build.

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project wso2: Failed during checkstyle execution: Unable to find suppressions file at location: https://raw.githubusercontent.com/wso2/code-quality-tools/master/checkstyle/suppressions.xml: Could not find resource 'https://raw.githubusercontent.com/wso2/code-quality-tools/master/checkstyle/suppressions.xml'. -> [Help 1]

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

> mvn clean package

**Related Issues:**

**Comment by delanym** [comment]
For whatever reason it now builds.

**Comment by kavishkafernando** [comment]
Encountered the same issue, it's because of the internet connection.
